### ISSUE TITLE
Expose SHADER_STRING in bindings

### ISSUE THREAD

**Issue by ArthurBrussee** [Swoorup/wgsl-bindgen#12]
Thanks for the great crate! Maybe a niche issue, but I'm using this to handle all the naga_oil preprocessing, generate some structs that have the correct layout, but otherwise I need to fit this in with an existin WGPU codebase (https://github.com/tracel-ai/burn). For that I need access to the final generated SHADER_STRING, which atm ends up as private.

Just have locally modified this for now, happy to create a PR if that sounds good!

**Comment by Swoorup** [comment]
Hmm, sure. That is something I didn't think of, but perfectly valid use case. I assume this is when using `WgslShaderSourceType::UseEmbed`

I am happy to accept a PR for that @ArthurBrussee 

You'll probably also need to update the integration tests that uses `UseEmbed` flag as well.

**Comment by ArthurBrussee** [comment]
Hey! Sorry for the late reply, that's really great to hear!

I've sent a PR here now *but* I ran into some issues while trying to run the tests, I think it'll require some care to get those running on Windows. Thanks again for having a look!

**Comment by Swoorup** [comment]
Thank you. Released https://crates.io/crates/wgsl_bindgen/0.10.1
