### ISSUE TITLE
wgpu 0.20 / naga_oil 0.14

### ISSUE THREAD

**Issue by ArthurBrussee** [Swoorup/wgsl-bindgen#15]
naga_oil 0.14 with support for wgpu 0.20 was just [released ](https://github.com/bevyengine/naga_oil/commit/93c1a645ec358a9b15765d4c09d43e4ee3de3fda)

 Besides bumping deps, shader_module.rs `ComputePipelineDescriptor` now needs

```
  compilation_options: Default::default(),
```

Or perhaps these options need to be exposed for consumers.

I've got a branch locally that works fine with this. Would submit a PR, but, testing on windows is broken atm, and that's too chunky for me to dig into atm.

Thanks a lot for having a look!

**Comment by Swoorup** [comment]
I am flexible with having them as `Default::default` until someone needs it. The changes to this library has been driven by use-cases. I'm bit busy on June, I'll start poking around soon.

**Comment by Swoorup** [comment]
Currently have a branch here: https://github.com/Swoorup/wgsl-bindgen/tree/sj-upgrade-wgpu

which has working test and example. I'll get around to adding actual support for pipeline overridable constants.

**Comment by Swoorup** [comment]
Fixed in https://github.com/Swoorup/wgsl-bindgen/pull/17

**Comment by Swoorup** [comment]
Released: https://crates.io/crates/wgsl_bindgen/0.12.0
