### ISSUE TITLE
example build error

### ISSUE THREAD

**Issue by songhuaixu** [Swoorup/wgsl-bindgen#32]
shader_bindings use ```include_abolute_path``` , it cannot run.
```include_abolute_path``` use ```proc_macro_span```  only rust nightly

**Comment by Swoorup** [comment]
It's a known problem, I am not sure of the solution right now as I need the absolute path feature for hot-reloading shaders.

**Comment by songhuaixu** [comment]
Thanks you, it works.  You can add a description in readme
