### ISSUE TITLE
Add constant counting number of buffers

### ISSUE THREAD

**Issue by hackaugusto** [Swoorup/wgsl-bindgen#4]
I got bitten by setting low `Limits` values by hand. It would be nice if code emitted by wgsl-bindgen included counters for the number of bind groups, uniforms, storage buffers and so on, to set the appropriate values in the `Limits` struct.

**Comment by Swoorup** [comment]
Wouldn't the default `wgpu::Limits` suffice?

**Comment by hackaugusto** [comment]
I initially had [Limits::downlevel_defaults()](https://docs.rs/wgpu/latest/wgpu/struct.Limits.html#method.downlevel_defaults), but the defaults are too low and caused issues. The documentation says:

> We recommend starting with the most restrictive limits you can and manually increasing the limits you need boosted. This will let you stay running on all hardware that supports the limits you need.

Having the counters would make that possible.

**Comment by Swoorup** [comment]
What about [`wgpu::Limits::default()` ](https://github.com/Swoorup/wgsl-bindgen/blob/main/example/src/main.rs#L49) like the example, which I think will just allow whatever the GPU supports? 

If you want to set specific limits, I am not sure this should be generated by the library, as it feels to me if user should manually set the lowest common denominator of the hardware they want to support.
